name: noted
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.4.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  provider: ^5.0.0
  intl: ^0.17.0
  flutter_markdown: ^0.6.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.4

flutter:
  fonts:
    - family: MontSerrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        


  uses-material-design: true
 
  